name: test
on:
  push:
    # branches: [main]
  pull_request:
    # branches: [main]
  merge_group:
    # types: [checks_requested]
jobs:
  check-aya-version:
    uses: aya-prover/aya-dev/.github/workflows/extract-version.yaml@main

  gradle-check:
    needs: [check-aya-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java ${{ needs.check-aya-version.outputs.javaVersion }}
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: ${{ needs.check-aya-version.outputs.javaVersion }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCodeCoverageReport --no-daemon --stacktrace --warning-mode all
      - name: Test report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: junit-tests
          report_paths: '**/build/test-results/test/TEST-*.xml'
      - name: Upload coverage to Codecov
        if: github.base_ref != null
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml
